# Generated by Django 5.0.7 on 2024-07-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('area_size', models.FloatField()),
                ('number_of_vehicles', models.IntegerField()),
                ('number_of_points', models.IntegerField()),
            ],
        ),
    ]
