# Generated by Django 5.0.7 on 2024-07-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmparameters',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithmparameters',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
